model:
  name: RadiomicMLP_PretrainedEnsembleResNet18Ft512_EfficientNetB2SFt1408
  subname: null # subname is used only for pretrained_models
  dropout: 0.3 # used in classification head
  out_channels: [5376, 1024, 512, 256] # fc layers in classification head
  pretrain: True # loads pretrained models
  separate_inputs: 3 # used in ensembled models currently
  radiomic_dims: [50, 256, 512, 1024] # Structure [in_dim, hidden_dim, out_dim]. in_dim is equal to no. of radiomic feature names. Used in radiomic + deep learning. If only in_dims is provided, then radiomic features are concatenated directly with the DL features, bypassing MLP networks.
  radiomic_activation: relu
  radiomic_dropout: 0.1 #null # 0.1
  radiomic_attention: BasicAttention # null # BasicAttention # used in radiomic + deep learning
  ft_normalization: [null, "bn"] # either None, "ln", or "bn"
  cls_activation: relu
  
train:
  epochs: 500
  lr: 0.0001 # 0.001
  weight_decay: 0.001
  save_weights_only: True
  save_best_model: True 
  save_last_model: False
  save_initial_model: False # useful in cross-validation, save a copy of the base model only
  period: 20
  early_stop: True
  patience: 70
  batch_size: 32
  one_hot: True
  n_classes: 2
  kfold: 5
  
test:
  base_model_name: null # RadiomicMLP_EnsembleResNet18Ft512_EfficientNetB2SFt1408_2024-11-20_16-36-23 # provide base_model_name if phase is test only
  type: both # option: best, average, both

phase: both # either train, test, or both
  
directories:
  root: /research/m324371/Project/adnexal/
  excel_dir: /research/m324371/Project/adnexal/adnexal_dataset_all.xlsx
  train_im_dir: /research/m324371/Project/adnexal/dataset/train/
  val_im_dir: /research/m324371/Project/adnexal/dataset/train/
  test_im_dir: /research/m324371/Project/adnexal/dataset/test/
  result_dir: /research/m324371/Project/adnexal/results/
  
data:
  only_adnexal: False
  only_fluid: True
  only_solid: True
  draw_bbox: False
  crop_roi: True
  margin: 200
  resize: True
  keep_aspect_ratio: True
  target_size: [224, 224]
  concat: ["image", "fluid", "solid"]

radiomic:
  train_dir: ["/research/m324371/Project/adnexal/radiomic_files/SelectKBest-k-50/Adnex_v2_radiomic_features_Params_filters_32_demo-Train-Val.csv"]
  
  test_dir: ["/research/m324371/Project/adnexal/radiomic_files/SelectKBest-k-50/Adnex_v2_radiomic_features_Params_filters_32_demo-test.csv"]
  
  yaml_dir: ["/research/m324371/Project/adnexal/radiomic_files/SelectKBest-k-50/Adnex_v2_radiomic_features_Params_filters_32_demo-Train-Val.yaml"]
  
  feature_type: long # either long or short
  
loss:
  name: ce
  
normalize:
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]

